### ISSUE TITLE
Try to reproduce the result

### ISSUE THREAD

**Issue by MengAaron** [AutoVision-cloud/Deformable-PV-RCNN#2]
I use 6 titan xp GPU and batch size is 6 to train 80 epoch. My result is 79.2,63.9,67.2. It much worse than yours, 83.31,59.31,74.18. What's your train epoch? Why does my result that bad?

**Comment by AutoVision-cloud** [comment]
Hi,
We use batch size 2 per GPU, and use 8 GPUs to train for 80 epochs.
For reproduction of the results, please also refer to the discussion in the PCDet library: 
https://github.com/open-mmlab/OpenPCDet/issues/250

**Comment by K-Young96** [comment]
@MengAaron @AutoVision-cloud    can you tell me how to check the mAP
