### ISSUE TITLE
Problem installing pcdet library 

### ISSUE THREAD

**Issue by MYSystemLogistics** [AutoVision-cloud/Deformable-PV-RCNN#3]
Hi,

when I try to install the pcdet library by running the command `sudo python3 setup.py develop` I got:

```
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from torch.utils.cpp_extension import BuildExtension, CUDAExtension
ModuleNotFoundError: No module named 'torch'
```
But it's strange since if I check my PyTorch version I got:
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__) 
1.6.0
```

All the requirements are satisfied, so how can I solve this problem?
Thank you for your attention.

**Comment by AutoVision-cloud** [comment]
Hi,
Are you using a docker or a virtual environment to setup PCDet?

**Comment by MYSystemLogistics** [comment]
Hi, actually I'm not using either of them. I will try with Anaconda and with Docker and let you know.
