### ISSUE TITLE
Who can share the detection results of PV-RCNN on nuscenes data set?

### ISSUE THREAD

**Issue by K-Young96** [AutoVision-cloud/Deformable-PV-RCNN#6]
Who can share the detection results of PV-RCNN on NUSCenes data set?
As the MEGVII test result format is given on the official website, it is divided into three parts: train , val and test .
Thanks !

**Comment by AutoVision-cloud** [comment]
Hey, thanks for your interest in this work. Right now we only evaluate this on KITTI but we welcome inputs from the community on other datasets as well.
